-- Backfill the theme every pre-theme workspace was already being shown.
--
-- Until now `theme IS NULL` meant "derive one from the icon at render time", so
-- the answer lived only in application code and every surface had to remember
-- to ask for it the same way -- which the settings picker did not, and so it
-- said "Default" over a card showing something else. This freezes that
-- derivation into the column once, using the same map the code used (first
-- theme listed per icon; compass excluded, being the app-wide fallback icon
-- that carries no subject). After this the column is the only source of truth
-- and the inference is deleted.
UPDATE `workspaces`
SET `theme` = CASE `icon`
		WHEN 'notebook-pen' THEN 'study-session'
		WHEN 'book-open-text' THEN 'lecture-notes'
		WHEN 'clock-3' THEN 'exam-prep'
		WHEN 'file-text' THEN 'coursework'
		WHEN 'book-marked' THEN 'reading-list'
		WHEN 'library-big' THEN 'library'
		WHEN 'school' THEN 'seminar'
		WHEN 'users' THEN 'study-group'
		WHEN 'graduation-cap' THEN 'graduation'
		WHEN 'highlighter' THEN 'highlights'
		WHEN 'book-search' THEN 'research-project'
		WHEN 'notebook-tabs' THEN 'literature-review'
		WHEN 'scroll-text' THEN 'thesis'
		WHEN 'archive' THEN 'citations'
		WHEN 'thermometer' THEN 'fieldwork'
		WHEN 'test-tube-diagonal' THEN 'lab-work'
		WHEN 'chart-scatter' THEN 'data-analysis'
		WHEN 'clipboard-list' THEN 'grant-proposal'
		WHEN 'folder-open' THEN 'knowledge-base'
		WHEN 'folder-search' THEN 'archive'
		WHEN 'lightbulb' THEN 'ideas'
		WHEN 'book-open' THEN 'reference'
		WHEN 'flask-conical' THEN 'chemistry'
		WHEN 'microscope' THEN 'biology'
		WHEN 'magnet' THEN 'physics'
		WHEN 'telescope' THEN 'astronomy'
		WHEN 'atom' THEN 'molecular-science'
		WHEN 'dna' THEN 'genetics'
		WHEN 'brain' THEN 'neuroscience'
		WHEN 'sigma' THEN 'mathematics'
		WHEN 'drafting-compass' THEN 'geometry'
		WHEN 'chart-column' THEN 'statistics'
		WHEN 'mountain' THEN 'earth-science'
		WHEN 'droplet' THEN 'climate'
		WHEN 'rocket' THEN 'space'
		WHEN 'zap' THEN 'electronics'
		WHEN 'stethoscope' THEN 'medicine'
		WHEN 'heart-pulse' THEN 'anatomy'
		WHEN 'pill' THEN 'pharmacy'
		WHEN 'hospital' THEN 'clinical'
		WHEN 'landmark' THEN 'history'
		WHEN 'ruler' THEN 'archaeology'
		WHEN 'map' THEN 'geography'
		WHEN 'globe-2' THEN 'world-studies'
		WHEN 'languages' THEN 'languages'
		WHEN 'pen-tool' THEN 'creative-writing'
		WHEN 'newspaper' THEN 'journalism'
		WHEN 'scale' THEN 'philosophy'
		WHEN 'gavel' THEN 'law'
		WHEN 'vote' THEN 'politics'
		WHEN 'brain-circuit' THEN 'psychology'
		WHEN 'message-square-text' THEN 'discussion'
		WHEN 'swatch-book' THEN 'design'
		WHEN 'pencil-ruler' THEN 'drawing'
		WHEN 'palette' THEN 'painting'
		WHEN 'camera' THEN 'photography'
		WHEN 'video' THEN 'film'
		WHEN 'theater' THEN 'theatre'
		WHEN 'music' THEN 'music'
		WHEN 'audio-lines' THEN 'instrument-practice'
		WHEN 'mic' THEN 'podcasting'
		WHEN 'headphones' THEN 'audio'
		WHEN 'code-2' THEN 'programming'
		WHEN 'binary' THEN 'web-development'
		WHEN 'database' THEN 'data-science'
		WHEN 'bot' THEN 'ai'
		WHEN 'cpu' THEN 'hardware'
		WHEN 'circuit-board' THEN 'robotics'
		WHEN 'shield-check' THEN 'cybersecurity'
		WHEN 'wrench' THEN 'engineering'
		WHEN 'satellite' THEN 'systems'
		WHEN 'briefcase-business' THEN 'business'
		WHEN 'target' THEN 'strategy'
		WHEN 'presentation' THEN 'meetings'
		WHEN 'chart-line' THEN 'analytics'
		WHEN 'file-chart-column' THEN 'reporting'
		WHEN 'banknote' THEN 'finance'
		WHEN 'calculator' THEN 'accounting'
		WHEN 'megaphone' THEN 'marketing'
		WHEN 'store' THEN 'sales'
		WHEN 'factory' THEN 'operations'
		WHEN 'truck' THEN 'logistics'
		WHEN 'kanban' THEN 'product'
		WHEN 'chart-gantt' THEN 'project-plan'
		WHEN 'orbit' THEN 'startup'
		WHEN 'handshake' THEN 'clients'
		WHEN 'building-2' THEN 'real-estate'
		WHEN 'calendar-days' THEN 'planner'
		WHEN 'list-todo' THEN 'to-do'
		WHEN 'search-check' THEN 'job-search'
		WHEN 'wallet-cards' THEN 'money'
		WHEN 'piggy-bank' THEN 'savings'
		WHEN 'receipt-text' THEN 'expenses'
		WHEN 'hand-coins' THEN 'home-diy'
		WHEN 'sprout' THEN 'gardening'
		WHEN 'earth' THEN 'travel'
		WHEN 'activity' THEN 'wellbeing'
		WHEN 'chart-pie' THEN 'economics'
		WHEN 'leaf' THEN 'ecology'
		WHEN 'cloud-sun' THEN 'environmental-science'
		WHEN 'pill-bottle' THEN 'nursing'
		WHEN 'waves' THEN 'public-health'
		WHEN 'helping-hand' THEN 'social-work'
		ELSE 'default'
	END
WHERE `theme` IS NULL;
