import { type AnyExtension, Extension, getSchema, mergeAttributes, Node } from "@tiptap/core";
import CodeBlock from "@tiptap/extension-code-block";
import Highlight from "@tiptap/extension-highlight";
import HorizontalRule from "@tiptap/extension-horizontal-rule";
import Link from "@tiptap/extension-link";
import { TaskItem, TaskList } from "@tiptap/extension-list";
import { Details, DetailsContent, DetailsSummary } from "@tiptap/extension-details";
import { Mathematics } from "@tiptap/extension-mathematics";
import { TableKit } from "@tiptap/extension-table";
import TextAlign from "@tiptap/extension-text-align";
import UnderlineExtension from "@tiptap/extension-underline";
import StarterKit from "@tiptap/starter-kit";

import {
	type WorkspaceLocation,
	workspaceLocationSchema,
} from "#/features/workspaces/locations/workspace-location";

export const tiptapDocumentYjsField = "default";

/**
 * A source reference inside a document. Holds the durable workspace location
 * rather than the short ref from one chat turn, so exact pages, blocks, and
 * cards keep working after the turn ends.
 */
export const Citation = Node.create({
	name: "citation",
	group: "inline",
	inline: true,
	atom: true,

	addAttributes() {
		return {
			itemId: { default: null, parseHTML: (el) => el.getAttribute("data-item-id") },
			blockId: { default: null, parseHTML: (el) => el.getAttribute("data-block-id") },
			cardId: { default: null, parseHTML: (el) => el.getAttribute("data-card-id") },
			pageNumber: {
				default: null,
				parseHTML: (el) => {
					const page = Number(el.getAttribute("data-page"));
					return Number.isInteger(page) && page > 0 ? page : null;
				},
			},
		};
	},

	parseHTML() {
		return [{ tag: "citation[data-item-id]" }];
	},

	renderHTML({ node }) {
		return [
			"citation",
			{
				"data-item-id": node.attrs.itemId,
				...(node.attrs.blockId ? { "data-block-id": String(node.attrs.blockId) } : {}),
				...(node.attrs.cardId ? { "data-card-id": String(node.attrs.cardId) } : {}),
				...(node.attrs.pageNumber ? { "data-page": String(node.attrs.pageNumber) } : {}),
			},
		];
	},
});

export function getDocumentCitationLocation(
	attrs: Record<string, unknown>,
): WorkspaceLocation | undefined {
	const itemId = typeof attrs.itemId === "string" ? attrs.itemId : null;
	if (!itemId) return undefined;

	const location = attrs.cardId
		? { cardId: attrs.cardId, itemId, kind: "flashcard", version: 1 }
		: attrs.blockId
			? { blockId: attrs.blockId, itemId, kind: "document-block", version: 1 }
			: attrs.pageNumber
				? { itemId, kind: "pdf-page", pageNumber: attrs.pageNumber, version: 1 }
				: { itemId, kind: "item", version: 1 };
	const parsed = workspaceLocationSchema.safeParse(location);

	return parsed.success ? parsed.data : undefined;
}
/**
 * An interactive widget: a self-contained HTML fragment the assistant writes,
 * rendered in a sandboxed iframe by the client's node view.
 *
 * The source is the node's text content rather than an attribute. A widget runs
 * to several kilobytes of markup and script, and escaping all of that into an
 * attribute is exactly the kind of thing a model gets subtly wrong — this is the
 * same reason a code block holds its code as content. `atom` means the editor
 * treats it as one unit: there is content, but it is not typed into directly.
 * `code` keeps input rules and smart typography from rewriting the source.
 */
export const Widget = Node.create({
	name: "widget",
	group: "block",
	content: "text*",
	marks: "",
	code: true,
	atom: true,
	defining: true,
	selectable: true,
	draggable: true,

	addAttributes() {
		return {
			title: {
				default: "",
				parseHTML: (el) => el.getAttribute("title") ?? "",
				renderHTML: (attrs) => (attrs.title ? { title: String(attrs.title) } : {}),
			},
		};
	},

	parseHTML() {
		return [{ tag: 'div[data-type="widget"]', preserveWhitespace: "full" as const }];
	},

	renderHTML({ HTMLAttributes }) {
		// Merge rather than replace: global attributes land here, and data-ref is
		// how the assistant addresses this block for reads and edits.
		return ["div", mergeAttributes(HTMLAttributes, { "data-type": "widget" }), 0];
	},
});

export const tiptapDocumentAiRefAttribute = "aiRef";

const DocumentAiRef = Extension.create({
	name: "documentAiRef",

	addGlobalAttributes() {
		const blockTypes = this.extensions
			.filter(
				(extension) =>
					extension.type === "node" &&
					typeof extension.config?.group === "string" &&
					extension.config.group.split(/\s+/).includes("block"),
			)
			.map((extension) => extension.name);

		return [
			{
				types: blockTypes,
				attributes: {
					[tiptapDocumentAiRefAttribute]: {
						default: null,
						// AI refs are generated by the document session. Pasted or model-authored
						// HTML must not be able to duplicate or choose them.
						parseHTML: () => null,
						renderHTML: (attributes: Record<string, unknown>) => {
							const ref = attributes[tiptapDocumentAiRefAttribute];
							return typeof ref === "string" && ref ? { "data-ref": ref } : {};
						},
					},
				},
			},
		];
	},
});

/**
 * Server-side code block extension. The editor swaps in `CodeBlockShiki`,
 * which extends the same `codeBlock` node spec, so JSON snapshots stay
 * compatible between server snapshots and session code and the live editor.
 */
export const tiptapDocumentServerCodeBlock = CodeBlock;

export function getTiptapDocumentSchemaExtensions({
	citation = Citation,
	codeBlock = tiptapDocumentServerCodeBlock,
	widget = Widget,
}: {
	citation?: AnyExtension;
	codeBlock?: AnyExtension;
	widget?: AnyExtension;
} = {}) {
	return [
		DocumentAiRef,
		citation,
		StarterKit.configure({
			heading: {
				levels: [1, 2, 3, 4],
			},
			codeBlock: false,
			horizontalRule: false,
			link: false,
			underline: false,
			undoRedo: false,
		}),
		codeBlock,
		widget,
		HorizontalRule,
		UnderlineExtension,
		Highlight,
		Link.configure({
			openOnClick: true,
			autolink: true,
			defaultProtocol: "https",
		}),
		Mathematics.configure({
			katexOptions: {
				throwOnError: false,
			},
		}),
		TextAlign.configure({
			types: ["heading", "paragraph"],
		}),
		// Collapsible sections. Registered for content only — the AI writes
		// <details> naturally and it used to be flattened away; there is no
		// toolbar affordance for inserting one by hand.
		Details,
		DetailsSummary,
		DetailsContent,
		TaskList,
		TaskItem.configure({
			nested: true,
		}),
		TableKit.configure({
			table: {
				lastColumnResizable: false,
				resizable: true,
			},
		}),
	];
}

const tiptapDocumentSchema = getSchema(getTiptapDocumentSchemaExtensions());

export function getTiptapDocumentSchema() {
	return tiptapDocumentSchema;
}
