/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AccountDeletedRouteImport } from './routes/account-deleted'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ApiV1WorkspacesRouteImport } from './routes/api/v1/workspaces'
import { Route as ApiPosthogSurveyFeedbackRouteImport } from './routes/api/posthog/survey-feedback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedWorkspacesWorkspaceIdRouteImport } from './routes/_protected/workspaces.$workspaceId'
import { Route as ProtectedSettingsConnectionsRouteImport } from './routes/_protected/settings/connections'
import { Route as DotwellKnownOauthProtectedResourceMcpRouteImport } from './routes/[.]well-known/oauth-protected-resource/mcp'
import { Route as ApiV1WorkspacesWorkspaceIdFileUploadRouteImport } from './routes/api/v1/workspaces.$workspaceId.file-upload'
import { Route as ApiV1WorkspacesWorkspaceIdChatAttachmentNormalizationRouteImport } from './routes/api/v1/workspaces.$workspaceId.chat-attachment-normalization'
import { Route as ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRouteImport } from './routes/api/v1/workspaces.$workspaceId.files.$itemId.preview'
import { Route as ApiV1WorkspacesWorkspaceIdFilesItemIdContentRouteImport } from './routes/api/v1/workspaces.$workspaceId.files.$itemId.content'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletedRoute = AccountDeletedRouteImport.update({
  id: '/account-deleted',
  path: '/account-deleted',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedSettingsRoute,
} as any)
const ApiV1WorkspacesRoute = ApiV1WorkspacesRouteImport.update({
  id: '/api/v1/workspaces',
  path: '/api/v1/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPosthogSurveyFeedbackRoute =
  ApiPosthogSurveyFeedbackRouteImport.update({
    id: '/api/posthog/survey-feedback',
    path: '/api/posthog/survey-feedback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWorkspacesWorkspaceIdRoute =
  ProtectedWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSettingsConnectionsRoute =
  ProtectedSettingsConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const DotwellKnownOauthProtectedResourceMcpRoute =
  DotwellKnownOauthProtectedResourceMcpRouteImport.update({
    id: '/.well-known/oauth-protected-resource/mcp',
    path: '/.well-known/oauth-protected-resource/mcp',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1WorkspacesWorkspaceIdFileUploadRoute =
  ApiV1WorkspacesWorkspaceIdFileUploadRouteImport.update({
    id: '/$workspaceId/file-upload',
    path: '/$workspaceId/file-upload',
    getParentRoute: () => ApiV1WorkspacesRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdChatAttachmentNormalizationRoute =
  ApiV1WorkspacesWorkspaceIdChatAttachmentNormalizationRouteImport.update({
    id: '/$workspaceId/chat-attachment-normalization',
    path: '/$workspaceId/chat-attachment-normalization',
    getParentRoute: () => ApiV1WorkspacesRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRoute =
  ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRouteImport.update({
    id: '/$workspaceId/files/$itemId/preview',
    path: '/$workspaceId/files/$itemId/preview',
    getParentRoute: () => ApiV1WorkspacesRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdFilesItemIdContentRoute =
  ApiV1WorkspacesWorkspaceIdFilesItemIdContentRouteImport.update({
    id: '/$workspaceId/files/$itemId/content',
    path: '/$workspaceId/files/$itemId/content',
    getParentRoute: () => ApiV1WorkspacesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-deleted': typeof AccountDeletedRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/home': typeof ProtectedHomeRoute
  '/settings': typeof ProtectedSettingsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.well-known/oauth-protected-resource/mcp': typeof DotwellKnownOauthProtectedResourceMcpRoute
  '/settings/connections': typeof ProtectedSettingsConnectionsRoute
  '/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/posthog/survey-feedback': typeof ApiPosthogSurveyFeedbackRoute
  '/api/v1/workspaces': typeof ApiV1WorkspacesRouteWithChildren
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/api/v1/workspaces/$workspaceId/chat-attachment-normalization': typeof ApiV1WorkspacesWorkspaceIdChatAttachmentNormalizationRoute
  '/api/v1/workspaces/$workspaceId/file-upload': typeof ApiV1WorkspacesWorkspaceIdFileUploadRoute
  '/api/v1/workspaces/$workspaceId/files/$itemId/content': typeof ApiV1WorkspacesWorkspaceIdFilesItemIdContentRoute
  '/api/v1/workspaces/$workspaceId/files/$itemId/preview': typeof ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deleted': typeof AccountDeletedRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/home': typeof ProtectedHomeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.well-known/oauth-protected-resource/mcp': typeof DotwellKnownOauthProtectedResourceMcpRoute
  '/settings/connections': typeof ProtectedSettingsConnectionsRoute
  '/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/posthog/survey-feedback': typeof ApiPosthogSurveyFeedbackRoute
  '/api/v1/workspaces': typeof ApiV1WorkspacesRouteWithChildren
  '/settings': typeof ProtectedSettingsIndexRoute
  '/api/v1/workspaces/$workspaceId/chat-attachment-normalization': typeof ApiV1WorkspacesWorkspaceIdChatAttachmentNormalizationRoute
  '/api/v1/workspaces/$workspaceId/file-upload': typeof ApiV1WorkspacesWorkspaceIdFileUploadRoute
  '/api/v1/workspaces/$workspaceId/files/$itemId/content': typeof ApiV1WorkspacesWorkspaceIdFilesItemIdContentRoute
  '/api/v1/workspaces/$workspaceId/files/$itemId/preview': typeof ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/account-deleted': typeof AccountDeletedRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/settings': typeof ProtectedSettingsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/.well-known/oauth-protected-resource/mcp': typeof DotwellKnownOauthProtectedResourceMcpRoute
  '/_protected/settings/connections': typeof ProtectedSettingsConnectionsRoute
  '/_protected/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/posthog/survey-feedback': typeof ApiPosthogSurveyFeedbackRoute
  '/api/v1/workspaces': typeof ApiV1WorkspacesRouteWithChildren
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/api/v1/workspaces/$workspaceId/chat-attachment-normalization': typeof ApiV1WorkspacesWorkspaceIdChatAttachmentNormalizationRoute
  '/api/v1/workspaces/$workspaceId/file-upload': typeof ApiV1WorkspacesWorkspaceIdFileUploadRoute
  '/api/v1/workspaces/$workspaceId/files/$itemId/content': typeof ApiV1WorkspacesWorkspaceIdFilesItemIdContentRoute
  '/api/v1/workspaces/$workspaceId/files/$itemId/preview': typeof ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-deleted'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/.well-known/oauth-authorization-server'
    | '/home'
    | '/settings'
    | '/invite/$token'
    | '/oauth/consent'
    | '/.well-known/oauth-protected-resource/mcp'
    | '/settings/connections'
    | '/workspaces/$workspaceId'
    | '/api/auth/$'
    | '/api/posthog/survey-feedback'
    | '/api/v1/workspaces'
    | '/settings/'
    | '/api/v1/workspaces/$workspaceId/chat-attachment-normalization'
    | '/api/v1/workspaces/$workspaceId/file-upload'
    | '/api/v1/workspaces/$workspaceId/files/$itemId/content'
    | '/api/v1/workspaces/$workspaceId/files/$itemId/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deleted'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/.well-known/oauth-authorization-server'
    | '/home'
    | '/invite/$token'
    | '/oauth/consent'
    | '/.well-known/oauth-protected-resource/mcp'
    | '/settings/connections'
    | '/workspaces/$workspaceId'
    | '/api/auth/$'
    | '/api/posthog/survey-feedback'
    | '/api/v1/workspaces'
    | '/settings'
    | '/api/v1/workspaces/$workspaceId/chat-attachment-normalization'
    | '/api/v1/workspaces/$workspaceId/file-upload'
    | '/api/v1/workspaces/$workspaceId/files/$itemId/content'
    | '/api/v1/workspaces/$workspaceId/files/$itemId/preview'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/account-deleted'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/.well-known/oauth-authorization-server'
    | '/_protected/home'
    | '/_protected/settings'
    | '/invite/$token'
    | '/oauth/consent'
    | '/.well-known/oauth-protected-resource/mcp'
    | '/_protected/settings/connections'
    | '/_protected/workspaces/$workspaceId'
    | '/api/auth/$'
    | '/api/posthog/survey-feedback'
    | '/api/v1/workspaces'
    | '/_protected/settings/'
    | '/api/v1/workspaces/$workspaceId/chat-attachment-normalization'
    | '/api/v1/workspaces/$workspaceId/file-upload'
    | '/api/v1/workspaces/$workspaceId/files/$itemId/content'
    | '/api/v1/workspaces/$workspaceId/files/$itemId/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AccountDeletedRoute: typeof AccountDeletedRoute
  CookiesRoute: typeof CookiesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OauthConsentRoute: typeof OauthConsentRoute
  DotwellKnownOauthProtectedResourceMcpRoute: typeof DotwellKnownOauthProtectedResourceMcpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPosthogSurveyFeedbackRoute: typeof ApiPosthogSurveyFeedbackRoute
  ApiV1WorkspacesRoute: typeof ApiV1WorkspacesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deleted': {
      id: '/account-deleted'
      path: '/account-deleted'
      fullPath: '/account-deleted'
      preLoaderRoute: typeof AccountDeletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/api/v1/workspaces': {
      id: '/api/v1/workspaces'
      path: '/api/v1/workspaces'
      fullPath: '/api/v1/workspaces'
      preLoaderRoute: typeof ApiV1WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posthog/survey-feedback': {
      id: '/api/posthog/survey-feedback'
      path: '/api/posthog/survey-feedback'
      fullPath: '/api/posthog/survey-feedback'
      preLoaderRoute: typeof ApiPosthogSurveyFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/workspaces/$workspaceId': {
      id: '/_protected/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/connections': {
      id: '/_protected/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof ProtectedSettingsConnectionsRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/.well-known/oauth-protected-resource/mcp': {
      id: '/.well-known/oauth-protected-resource/mcp'
      path: '/.well-known/oauth-protected-resource/mcp'
      fullPath: '/.well-known/oauth-protected-resource/mcp'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/workspaces/$workspaceId/file-upload': {
      id: '/api/v1/workspaces/$workspaceId/file-upload'
      path: '/$workspaceId/file-upload'
      fullPath: '/api/v1/workspaces/$workspaceId/file-upload'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdFileUploadRouteImport
      parentRoute: typeof ApiV1WorkspacesRoute
    }
    '/api/v1/workspaces/$workspaceId/chat-attachment-normalization': {
      id: '/api/v1/workspaces/$workspaceId/chat-attachment-normalization'
      path: '/$workspaceId/chat-attachment-normalization'
      fullPath: '/api/v1/workspaces/$workspaceId/chat-attachment-normalization'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdChatAttachmentNormalizationRouteImport
      parentRoute: typeof ApiV1WorkspacesRoute
    }
    '/api/v1/workspaces/$workspaceId/files/$itemId/preview': {
      id: '/api/v1/workspaces/$workspaceId/files/$itemId/preview'
      path: '/$workspaceId/files/$itemId/preview'
      fullPath: '/api/v1/workspaces/$workspaceId/files/$itemId/preview'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRouteImport
      parentRoute: typeof ApiV1WorkspacesRoute
    }
    '/api/v1/workspaces/$workspaceId/files/$itemId/content': {
      id: '/api/v1/workspaces/$workspaceId/files/$itemId/content'
      path: '/$workspaceId/files/$itemId/content'
      fullPath: '/api/v1/workspaces/$workspaceId/files/$itemId/content'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdFilesItemIdContentRouteImport
      parentRoute: typeof ApiV1WorkspacesRoute
    }
  }
}

interface ProtectedSettingsRouteChildren {
  ProtectedSettingsConnectionsRoute: typeof ProtectedSettingsConnectionsRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
}

const ProtectedSettingsRouteChildren: ProtectedSettingsRouteChildren = {
  ProtectedSettingsConnectionsRoute: ProtectedSettingsConnectionsRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
}

const ProtectedSettingsRouteWithChildren =
  ProtectedSettingsRoute._addFileChildren(ProtectedSettingsRouteChildren)

interface ProtectedRouteChildren {
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRouteWithChildren
  ProtectedWorkspacesWorkspaceIdRoute: typeof ProtectedWorkspacesWorkspaceIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedSettingsRoute: ProtectedSettingsRouteWithChildren,
  ProtectedWorkspacesWorkspaceIdRoute: ProtectedWorkspacesWorkspaceIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface ApiV1WorkspacesRouteChildren {
  ApiV1WorkspacesWorkspaceIdChatAttachmentNormalizationRoute: typeof ApiV1WorkspacesWorkspaceIdChatAttachmentNormalizationRoute
  ApiV1WorkspacesWorkspaceIdFileUploadRoute: typeof ApiV1WorkspacesWorkspaceIdFileUploadRoute
  ApiV1WorkspacesWorkspaceIdFilesItemIdContentRoute: typeof ApiV1WorkspacesWorkspaceIdFilesItemIdContentRoute
  ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRoute: typeof ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRoute
}

const ApiV1WorkspacesRouteChildren: ApiV1WorkspacesRouteChildren = {
  ApiV1WorkspacesWorkspaceIdChatAttachmentNormalizationRoute:
    ApiV1WorkspacesWorkspaceIdChatAttachmentNormalizationRoute,
  ApiV1WorkspacesWorkspaceIdFileUploadRoute:
    ApiV1WorkspacesWorkspaceIdFileUploadRoute,
  ApiV1WorkspacesWorkspaceIdFilesItemIdContentRoute:
    ApiV1WorkspacesWorkspaceIdFilesItemIdContentRoute,
  ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRoute:
    ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRoute,
}

const ApiV1WorkspacesRouteWithChildren = ApiV1WorkspacesRoute._addFileChildren(
  ApiV1WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AccountDeletedRoute: AccountDeletedRoute,
  CookiesRoute: CookiesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  InviteTokenRoute: InviteTokenRoute,
  OauthConsentRoute: OauthConsentRoute,
  DotwellKnownOauthProtectedResourceMcpRoute:
    DotwellKnownOauthProtectedResourceMcpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPosthogSurveyFeedbackRoute: ApiPosthogSurveyFeedbackRoute,
  ApiV1WorkspacesRoute: ApiV1WorkspacesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
