/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AccountDeletedRouteImport } from './routes/account-deleted'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as BlogRssRouteImport } from './routes/blog.rss'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'
import { Route as ApiV1WorkspacesRouteImport } from './routes/api/v1/workspaces'
import { Route as ApiPosthogSurveyFeedbackRouteImport } from './routes/api/posthog/survey-feedback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedWorkspacesWorkspaceIdRouteImport } from './routes/_protected/workspaces.$workspaceId'
import { Route as ApiV1WorkspacesWorkspaceIdFileUploadRouteImport } from './routes/api/v1/workspaces.$workspaceId.file-upload'
import { Route as ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRouteImport } from './routes/api/v1/workspaces.$workspaceId.files.$itemId.preview'
import { Route as ApiV1WorkspacesWorkspaceIdFilesItemIdContentRouteImport } from './routes/api/v1/workspaces.$workspaceId.files.$itemId.content'
import { Route as ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRouteImport } from './routes/api/v1/workspaces.$workspaceId.ai-threads.$threadId.attachments'
import { Route as ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsAttachmentIdRouteImport } from './routes/api/v1/workspaces.$workspaceId.ai-threads.$threadId.attachments.$attachmentId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDeletedRoute = AccountDeletedRouteImport.update({
  id: '/account-deleted',
  path: '/account-deleted',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRssRoute = BlogRssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiV1WorkspacesRoute = ApiV1WorkspacesRouteImport.update({
  id: '/api/v1/workspaces',
  path: '/api/v1/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPosthogSurveyFeedbackRoute =
  ApiPosthogSurveyFeedbackRouteImport.update({
    id: '/api/posthog/survey-feedback',
    path: '/api/posthog/survey-feedback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWorkspacesWorkspaceIdRoute =
  ProtectedWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdFileUploadRoute =
  ApiV1WorkspacesWorkspaceIdFileUploadRouteImport.update({
    id: '/$workspaceId/file-upload',
    path: '/$workspaceId/file-upload',
    getParentRoute: () => ApiV1WorkspacesRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRoute =
  ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRouteImport.update({
    id: '/$workspaceId/files/$itemId/preview',
    path: '/$workspaceId/files/$itemId/preview',
    getParentRoute: () => ApiV1WorkspacesRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdFilesItemIdContentRoute =
  ApiV1WorkspacesWorkspaceIdFilesItemIdContentRouteImport.update({
    id: '/$workspaceId/files/$itemId/content',
    path: '/$workspaceId/files/$itemId/content',
    getParentRoute: () => ApiV1WorkspacesRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRoute =
  ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRouteImport.update({
    id: '/$workspaceId/ai-threads/$threadId/attachments',
    path: '/$workspaceId/ai-threads/$threadId/attachments',
    getParentRoute: () => ApiV1WorkspacesRoute,
  } as any)
const ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsAttachmentIdRoute =
  ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsAttachmentIdRouteImport.update(
    {
      id: '/$attachmentId',
      path: '/$attachmentId',
      getParentRoute: () =>
        ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-deleted': typeof AccountDeletedRoute
  '/blog': typeof BlogRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/home': typeof ProtectedHomeRoute
  '/settings': typeof ProtectedSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss': typeof BlogRssRoute
  '/invite/$token': typeof InviteTokenRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/blog/': typeof BlogIndexRoute
  '/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/posthog/survey-feedback': typeof ApiPosthogSurveyFeedbackRoute
  '/api/v1/workspaces': typeof ApiV1WorkspacesRouteWithChildren
  '/api/v1/workspaces/$workspaceId/file-upload': typeof ApiV1WorkspacesWorkspaceIdFileUploadRoute
  '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments': typeof ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/files/$itemId/content': typeof ApiV1WorkspacesWorkspaceIdFilesItemIdContentRoute
  '/api/v1/workspaces/$workspaceId/files/$itemId/preview': typeof ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRoute
  '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments/$attachmentId': typeof ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsAttachmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-deleted': typeof AccountDeletedRoute
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/home': typeof ProtectedHomeRoute
  '/settings': typeof ProtectedSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss': typeof BlogRssRoute
  '/invite/$token': typeof InviteTokenRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/blog': typeof BlogIndexRoute
  '/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/posthog/survey-feedback': typeof ApiPosthogSurveyFeedbackRoute
  '/api/v1/workspaces': typeof ApiV1WorkspacesRouteWithChildren
  '/api/v1/workspaces/$workspaceId/file-upload': typeof ApiV1WorkspacesWorkspaceIdFileUploadRoute
  '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments': typeof ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/files/$itemId/content': typeof ApiV1WorkspacesWorkspaceIdFilesItemIdContentRoute
  '/api/v1/workspaces/$workspaceId/files/$itemId/preview': typeof ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRoute
  '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments/$attachmentId': typeof ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsAttachmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/account-deleted': typeof AccountDeletedRoute
  '/blog': typeof BlogRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss': typeof BlogRssRoute
  '/invite/$token': typeof InviteTokenRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/blog/': typeof BlogIndexRoute
  '/_protected/workspaces/$workspaceId': typeof ProtectedWorkspacesWorkspaceIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/posthog/survey-feedback': typeof ApiPosthogSurveyFeedbackRoute
  '/api/v1/workspaces': typeof ApiV1WorkspacesRouteWithChildren
  '/api/v1/workspaces/$workspaceId/file-upload': typeof ApiV1WorkspacesWorkspaceIdFileUploadRoute
  '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments': typeof ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRouteWithChildren
  '/api/v1/workspaces/$workspaceId/files/$itemId/content': typeof ApiV1WorkspacesWorkspaceIdFilesItemIdContentRoute
  '/api/v1/workspaces/$workspaceId/files/$itemId/preview': typeof ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRoute
  '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments/$attachmentId': typeof ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsAttachmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-deleted'
    | '/blog'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/home'
    | '/settings'
    | '/blog/$slug'
    | '/blog/rss'
    | '/invite/$token'
    | '/oauth/consent'
    | '/blog/'
    | '/workspaces/$workspaceId'
    | '/api/auth/$'
    | '/api/posthog/survey-feedback'
    | '/api/v1/workspaces'
    | '/api/v1/workspaces/$workspaceId/file-upload'
    | '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments'
    | '/api/v1/workspaces/$workspaceId/files/$itemId/content'
    | '/api/v1/workspaces/$workspaceId/files/$itemId/preview'
    | '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments/$attachmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-deleted'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/home'
    | '/settings'
    | '/blog/$slug'
    | '/blog/rss'
    | '/invite/$token'
    | '/oauth/consent'
    | '/blog'
    | '/workspaces/$workspaceId'
    | '/api/auth/$'
    | '/api/posthog/survey-feedback'
    | '/api/v1/workspaces'
    | '/api/v1/workspaces/$workspaceId/file-upload'
    | '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments'
    | '/api/v1/workspaces/$workspaceId/files/$itemId/content'
    | '/api/v1/workspaces/$workspaceId/files/$itemId/preview'
    | '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments/$attachmentId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/account-deleted'
    | '/blog'
    | '/cookies'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/_protected/home'
    | '/_protected/settings'
    | '/blog/$slug'
    | '/blog/rss'
    | '/invite/$token'
    | '/oauth/consent'
    | '/blog/'
    | '/_protected/workspaces/$workspaceId'
    | '/api/auth/$'
    | '/api/posthog/survey-feedback'
    | '/api/v1/workspaces'
    | '/api/v1/workspaces/$workspaceId/file-upload'
    | '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments'
    | '/api/v1/workspaces/$workspaceId/files/$itemId/content'
    | '/api/v1/workspaces/$workspaceId/files/$itemId/preview'
    | '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments/$attachmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AccountDeletedRoute: typeof AccountDeletedRoute
  BlogRoute: typeof BlogRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OauthConsentRoute: typeof OauthConsentRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPosthogSurveyFeedbackRoute: typeof ApiPosthogSurveyFeedbackRoute
  ApiV1WorkspacesRoute: typeof ApiV1WorkspacesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-deleted': {
      id: '/account-deleted'
      path: '/account-deleted'
      fullPath: '/account-deleted'
      preLoaderRoute: typeof AccountDeletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/rss': {
      id: '/blog/rss'
      path: '/rss'
      fullPath: '/blog/rss'
      preLoaderRoute: typeof BlogRssRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/v1/workspaces': {
      id: '/api/v1/workspaces'
      path: '/api/v1/workspaces'
      fullPath: '/api/v1/workspaces'
      preLoaderRoute: typeof ApiV1WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posthog/survey-feedback': {
      id: '/api/posthog/survey-feedback'
      path: '/api/posthog/survey-feedback'
      fullPath: '/api/posthog/survey-feedback'
      preLoaderRoute: typeof ApiPosthogSurveyFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/workspaces/$workspaceId': {
      id: '/_protected/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof ProtectedWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/v1/workspaces/$workspaceId/file-upload': {
      id: '/api/v1/workspaces/$workspaceId/file-upload'
      path: '/$workspaceId/file-upload'
      fullPath: '/api/v1/workspaces/$workspaceId/file-upload'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdFileUploadRouteImport
      parentRoute: typeof ApiV1WorkspacesRoute
    }
    '/api/v1/workspaces/$workspaceId/files/$itemId/preview': {
      id: '/api/v1/workspaces/$workspaceId/files/$itemId/preview'
      path: '/$workspaceId/files/$itemId/preview'
      fullPath: '/api/v1/workspaces/$workspaceId/files/$itemId/preview'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRouteImport
      parentRoute: typeof ApiV1WorkspacesRoute
    }
    '/api/v1/workspaces/$workspaceId/files/$itemId/content': {
      id: '/api/v1/workspaces/$workspaceId/files/$itemId/content'
      path: '/$workspaceId/files/$itemId/content'
      fullPath: '/api/v1/workspaces/$workspaceId/files/$itemId/content'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdFilesItemIdContentRouteImport
      parentRoute: typeof ApiV1WorkspacesRoute
    }
    '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments': {
      id: '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments'
      path: '/$workspaceId/ai-threads/$threadId/attachments'
      fullPath: '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRouteImport
      parentRoute: typeof ApiV1WorkspacesRoute
    }
    '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments/$attachmentId': {
      id: '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments/$attachmentId'
      path: '/$attachmentId'
      fullPath: '/api/v1/workspaces/$workspaceId/ai-threads/$threadId/attachments/$attachmentId'
      preLoaderRoute: typeof ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsAttachmentIdRouteImport
      parentRoute: typeof ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedWorkspacesWorkspaceIdRoute: typeof ProtectedWorkspacesWorkspaceIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedWorkspacesWorkspaceIdRoute: ProtectedWorkspacesWorkspaceIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogRssRoute: typeof BlogRssRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogRssRoute: BlogRssRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRouteChildren {
  ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsAttachmentIdRoute: typeof ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsAttachmentIdRoute
}

const ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRouteChildren: ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRouteChildren =
  {
    ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsAttachmentIdRoute:
      ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsAttachmentIdRoute,
  }

const ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRouteWithChildren =
  ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRoute._addFileChildren(
    ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRouteChildren,
  )

interface ApiV1WorkspacesRouteChildren {
  ApiV1WorkspacesWorkspaceIdFileUploadRoute: typeof ApiV1WorkspacesWorkspaceIdFileUploadRoute
  ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRoute: typeof ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRouteWithChildren
  ApiV1WorkspacesWorkspaceIdFilesItemIdContentRoute: typeof ApiV1WorkspacesWorkspaceIdFilesItemIdContentRoute
  ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRoute: typeof ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRoute
}

const ApiV1WorkspacesRouteChildren: ApiV1WorkspacesRouteChildren = {
  ApiV1WorkspacesWorkspaceIdFileUploadRoute:
    ApiV1WorkspacesWorkspaceIdFileUploadRoute,
  ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRoute:
    ApiV1WorkspacesWorkspaceIdAiThreadsThreadIdAttachmentsRouteWithChildren,
  ApiV1WorkspacesWorkspaceIdFilesItemIdContentRoute:
    ApiV1WorkspacesWorkspaceIdFilesItemIdContentRoute,
  ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRoute:
    ApiV1WorkspacesWorkspaceIdFilesItemIdPreviewRoute,
}

const ApiV1WorkspacesRouteWithChildren = ApiV1WorkspacesRoute._addFileChildren(
  ApiV1WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AccountDeletedRoute: AccountDeletedRoute,
  BlogRoute: BlogRouteWithChildren,
  CookiesRoute: CookiesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  InviteTokenRoute: InviteTokenRoute,
  OauthConsentRoute: OauthConsentRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPosthogSurveyFeedbackRoute: ApiPosthogSurveyFeedbackRoute,
  ApiV1WorkspacesRoute: ApiV1WorkspacesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
